import { Color } from 'three';
import { STAGE_BANNERS } from 'sprites';
import GameConfig from './GameConfig.js';

const WORDS = {
    0: [
        'cat',
        'sun',
        'apple',
        'hope',
        'was',
        'beach',
        'chair',
        'dog',
        'elf',
        'lover',
        'fox',
        'igloo',
        'pixel',
        'color',
        'giraffe',
        'ray',
        'kind',
        'lizard',
        'muffin',
        'nap',
        'ostrich',
        'pillow',
        'queen',
        'rizz',
        'star',
        'tea',
        'unite',
        'zen',
        'lace',
        'pool',
    ],
    1: [
        'cat',
        'sun',
        'apple',
        'hope',
        'was',
        'beach',
        'chair',
        'dog',
        'elf',
        'lover',
        'fox',
        'igloo',
        'pixel',
        'color',
        'giraffe',
        'ray',
        'kind',
        'lizard',
        'muffin',
        'nap',
        'ostrich',
        'pillow',
        'queen',
        'rizz',
        'star',
        'tea',
        'unite',
        'zen',
        'lace',
        'pool',
        'blubber',
        'chicken',
        'really',
        'joy',
        'katie',
        'andrew',
        'genie',
        'purple',
        'banana',
        'happy',
        'guitar',
        'basket',
        'butter',
        'planet',
        'silver',
        'laptop',
        'monkey',
        'orange',
        'dragon',
        'turtle',
        'whisper',
        'kangaroo',
        'sparkle',
        'render',
        'shader',
        'gradient',
        'palette',
        'animation',
        'resolution',
        'opacity',
    ],
    2: [
        'cat',
        'sun',
        'apple',
        'hope',
        'was',
        'beach',
        'chair',
        'dog',
        'elf',
        'lover',
        'fox',
        'igloo',
        'pixel',
        'color',
        'giraffe',
        'ray',
        'kind',
        'lizard',
        'muffin',
        'nap',
        'ostrich',
        'pillow',
        'queen',
        'rizz',
        'star',
        'tea',
        'unite',
        'zen',
        'lace',
        'pool',
        'blubber',
        'chicken',
        'really',
        'joy',
        'katie',
        'andrew',
        'genie',
        'purple',
        'banana',
        'happy',
        'guitar',
        'basket',
        'butter',
        'planet',
        'silver',
        'laptop',
        'monkey',
        'orange',
        'dragon',
        'turtle',
        'whisper',
        'kangaroo',
        'sparkle',
        'render',
        'shader',
        'gradient',
        'palette',
        'animation',
        'resolution',
        'opacity',
        'refraction',
        'reflection',
        'rasterization',
        'polygon',
        'ambient',
        'diffuse',
        'specular',
        'mapping',
        'blending',
        'shadow',
        'lighting',
        'saturation',
        'brightness',
        'waterfall',
        'renaissance',
        'nostalgia',
        'princeton',
        'metamorphosis',
        'astronomy',
        'treasure',
        'rainbow',
        'disappear',
        'encyclopedia',
        'boulevard',
        'gratitude',
        'hemisphere',
        'juxtapose',
        'silhouette',
        'entrepreneur',
        'luminosity',
    ],
};

const SPEEDS = {
    0: [0.5, 1],
    1: [0.8, 1.5],
    2: [1.2, 2],
};

export const STAGE_CONFIGS = {
    0: new GameConfig(
        3,
        WORDS[0],
        [2, 3],
        [4, 6],
        new Color(0x7ec0ee),
        5,
        STAGE_BANNERS[0]
    ),
    1: new GameConfig(
        3,
        WORDS[1],
        [1, 2],
        [4, 6],
        new Color(0xaec077),
        5,
        STAGE_BANNERS[1]
    ),
    2: new GameConfig(
        10,
        WORDS[2],
        [0.5, 1.5],
        [4, 6],
        new Color(0xee7777),
        250,
        STAGE_BANNERS[2]
    ),
};
